version: "3"
services:
 app:
  container_name: app2
  image: mohinig33/attendance
  restart: always
  build: .
  ports:
  - "3002:3002"
  links:
  - mongo

 mongo:
  container_name: mongo
  image: mongo
  volumes:
  - ./data:/data/db
  ports:
  - '27017:27017'