apiVersion: v1
kind: Service
metdata:
 name: attendance-service
spec:
  selector:
    app: attendance
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3002
    nodePort: 31110